"""Add quiz name with default

Revision ID: e9cfc6a8dd9c
Revises: 
Create Date: 2025-07-27 22:17:20.386585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cfc6a8dd9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), server_default='Untitled Quiz', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
